version: '3.4'

services:
  inventorium:
    image: ${DOCKER_REGISTRY-}inventorium
    build:
      context: .
      dockerfile: Inventorium/Dockerfile

  sql-express:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
      - MSSQL_SA_PASSWORD=1000Items!
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - /data:/var/opt/mssql/data
      - /log:/var/opt/mssql/log
      - /secrets:/var/opt/mssql/secrets
